export type ToolCategory =
  | 'text'
  | 'image'
  | 'code'
  | 'conversion'
  | 'encoding'
  | 'generator'
  | 'security'
  | 'network';

export interface ToolMeta {
  id: string;
  name: string;
  icon: string;
  category: ToolCategory;
  description: string;
  tags: string[];
}

const registry: ToolMeta[] = [
  {
    id: 'text-diff',
    name: '文本差异对比',
    icon: 'difference',
    category: 'text',
    description: '高亮显示两段文本的逐行差异',
    tags: ['diff', 'compare', '对比', '差异', '文本'],
  },
  {
    id: 'full-half-width',
    name: '全半角转换',
    icon: 'swap_horiz',
    category: 'text',
    description: '中英文全角半角字符互转',
    tags: ['全角', '半角', '转换', 'text'],
  },
  {
    id: 'char-count',
    name: '字符统计',
    icon: 'abc',
    category: 'text',
    description: '统计文本的字符数、单词数、行数',
    tags: ['count', '统计', '字符', '字数'],
  },
  {
    id: 'text-dedup',
    name: '文本去重',
    icon: 'content_copy',
    category: 'text',
    description: '去除重复行，支持排序',
    tags: ['dedup', '去重', '重复'],
  },
  {
    id: 'word-extract',
    name: '单词提取',
    icon: 'dictionary',
    category: 'text',
    description: '从文本中提取所有不重复的单词',
    tags: ['word', '提取', '单词'],
  },
  {
    id: 'text-replace',
    name: '文本替换与提取',
    icon: 'find_replace',
    category: 'text',
    description: '批量查找替换文本内容，支持正则',
    tags: ['replace', '替换', '查找', '提取', '文本'],
  },
  {
    id: 'char-counter',
    name: '字符文字计数器',
    icon: 'counter',
    category: 'text',
    description: '详细统计字符、中英文、数字、标点数量',
    tags: ['count', '计数', '字符', '统计', '详细'],
  },
  {
    id: 'case-converter',
    name: '大小写转换器',
    icon: 'text_fields',
    category: 'text',
    description: '文本大小写格式转换',
    tags: ['case', '大小写', '转换', 'upper', 'lower'],
  },
  {
    id: 'cn-traditional',
    name: '繁简中文转换器',
    icon: 'translate',
    category: 'text',
    description: '简体中文与繁体中文互转',
    tags: ['繁体', '简体', '中文', '转换', 'traditional', 'simplified'],
  },
  {
    id: 'en-case',
    name: '英文大小写转化器',
    icon: 'title',
    category: 'text',
    description: '英文句子/标题/大小写转换',
    tags: ['english', 'case', 'title', 'sentence', '英文', '大小写'],
  },
  {
    id: 'hanzi-pinyin',
    name: '汉字转拼音',
    icon: 'record_voice_over',
    category: 'text',
    description: '将中文汉字转换为拼音',
    tags: ['pinyin', '拼音', '汉字', '中文', '发音'],
  },
  {
    id: 'md-to-word',
    name: 'Markdown 转 Word',
    icon: 'description',
    category: 'conversion',
    description: '将 Markdown 文本转换为 Word 文档',
    tags: ['markdown', 'word', 'docx', '文档', '转换'],
  },
  {
    id: 'json-formatter',
    name: 'JSON 格式化',
    icon: 'data_object',
    category: 'code',
    description: '格式化、压缩、验证 JSON 数据',
    tags: ['json', 'format', '格式化', '压缩'],
  },
  {
    id: 'code-beautify',
    name: '代码美化',
    icon: 'code',
    category: 'code',
    description: 'HTML / CSS / JS 代码格式化',
    tags: ['code', 'beautify', '美化', '格式化'],
  },
  {
    id: 'html-code-runner',
    name: 'HTML/CSS/JS 在线运行',
    icon: 'javascript',
    category: 'code',
    description: '粘贴代码一键运行，实时预览页面渲染效果',
    tags: ['html', 'css', 'javascript', 'js', 'run', 'preview', '代码运行', '实时预览'],
  },
  {
    id: 'regex-test',
    name: '正则测试',
    icon: 'regular_expression',
    category: 'code',
    description: '实时测试正则表达式匹配',
    tags: ['regex', '正则', '匹配'],
  },
  {
    id: 'markdown-preview',
    name: 'Markdown 文件预览器',
    icon: 'preview',
    category: 'code',
    description: 'Markdown 实时预览，支持代码高亮、表格和流程图',
    tags: ['markdown', 'preview', '预览', '渲染', 'flowchart'],
  },
  {
    id: 'code-highlight',
    name: '代码高亮工具',
    icon: 'palette',
    category: 'code',
    description: '代码语法高亮，支持多种语言，可导出 HTML',
    tags: ['code', 'highlight', '高亮', '语法', 'syntax'],
  },
  {
    id: 'image-base64-code',
    name: '图片Base64互换',
    icon: 'swap_horiz',
    category: 'encoding',
    description: '图片文件与 Base64 编码字符串双向转换',
    tags: ['image', 'base64', '图片', '编码', '互换'],
  },
  {
    id: 'svg-to-base64',
    name: 'SVG转Base64',
    icon: 'scissors',
    category: 'encoding',
    description: '将 SVG 代码或文件转换为 Base64 编码',
    tags: ['svg', 'base64', '编码', '图片'],
  },
  {
    id: 'ascii-art',
    name: 'ASCII文字图片生成器',
    icon: 'font',
    category: 'generator',
    description: '将文本转换为 ASCII 字符艺术图案',
    tags: ['ascii', 'art', '字符', '生成', '文字图片'],
  },
  {
    id: 'sql-er-diagram',
    name: 'ER 实体关系图',
    icon: 'network',
    category: 'code',
    description: '从 SQL DDL 生成 Chen 记法实体关系图，支持拖拽编辑、实时预览和导出',
    tags: ['sql', 'er', 'diagram', '数据库', 'ER图', 'chen', '实体关系'],
  },
  {
    id: 'mermaid-flowchart',
    name: 'Mermaid 流程图',
    icon: 'flowchart',
    category: 'code',
    description: '使用 Mermaid 语法在线绘制流程图，支持实时预览、缩放和导出',
    tags: ['mermaid', 'flowchart', '流程图', '图表', 'graph', 'diagram'],
  },
  {
    id: 'password-gen',
    name: '密码生成器',
    icon: 'password',
    category: 'security',
    description: '生成安全随机密码',
    tags: ['password', '密码', '生成', '安全'],
  },
  {
    id: 'uuid-gen',
    name: 'UUID 生成器',
    icon: 'tag',
    category: 'generator',
    description: '生成 v4 UUID',
    tags: ['uuid', '生成', 'id'],
  },
  {
    id: 'lorem-gen',
    name: '占位文生成',
    icon: 'article',
    category: 'generator',
    description: '生成 Lorem Ipsum 占位文本',
    tags: ['lorem', '占位', '生成', 'placeholder'],
  },
  {
    id: 'qr-code',
    name: '二维码生成',
    icon: 'qr_code_2',
    category: 'generator',
    description: '将文本转换为二维码',
    tags: ['qr', '二维码', '生成'],
  },
  {
    id: 'qr-scan',
    name: '二维码扫描',
    icon: 'qr_code_scanner',
    category: 'image',
    description: '通过摄像头或图片识别二维码',
    tags: ['qr', '二维码', '扫描', '识别', 'scan'],
  },
  {
    id: 'base64',
    name: 'Base64 编码',
    icon: 'code',
    category: 'encoding',
    description: '文本与 Base64 互转',
    tags: ['base64', '编码', '解码', '转换'],
  },
  {
    id: 'url-encode',
    name: 'URL 编码',
    icon: 'link',
    category: 'encoding',
    description: 'URL 编码与解码',
    tags: ['url', '编码', '解码', 'encode'],
  },
  {
    id: 'unicode',
    name: 'Unicode 编解码器',
    icon: 'text_fields',
    category: 'encoding',
    description: '文本与 Unicode 转义序列互转',
    tags: ['unicode', '编码', '解码', '转义', '\\u'],
  },
  {
    id: 'base-x',
    name: 'BaseX 编解码器',
    icon: 'binary',
    category: 'encoding',
    description: '支持 Base32 / Base58 / Base62 编解码',
    tags: ['base32', 'base58', 'base62', '编码', '解码'],
  },
  {
    id: 'morse',
    name: '摩斯密码转换器',
    icon: 'morse',
    category: 'encoding',
    description: '文本与摩斯密码互转',
    tags: ['morse', '摩斯', '密码', '电报'],
  },
  {
    id: 'jwt-decode',
    name: 'JWT 解码器',
    icon: 'key',
    category: 'encoding',
    description: '解码 JWT Token 查看 Header 和 Payload',
    tags: ['jwt', 'token', '解码', 'json web token'],
  },
  {
    id: 'ip-query',
    name: 'IP 地址查询',
    icon: 'language',
    category: 'network',
    description: '查询当前公网 IP 地址',
    tags: ['ip', '查询', '网络'],
  },
  {
    id: 'online-ping',
    name: '在线 Ping',
    icon: 'send',
    category: 'network',
    description: '在线 Ping 测试工具',
    tags: ['ping', '网络', '延迟', '测试'],
  },
  {
    id: 'online-tcping',
    name: '在线 TCPing',
    icon: 'wifi',
    category: 'network',
    description: '在线 TCP 端口连通性测试',
    tags: ['tcping', 'tcp', '端口', '网络'],
  },
  {
    id: 'website-speed',
    name: '网站测速',
    icon: 'speedometer',
    category: 'network',
    description: '在线网站访问速度测试',
    tags: ['speed', '测速', '网站', '网络'],
  },
  {
    id: 'traceroute',
    name: '路由追踪',
    icon: 'route',
    category: 'network',
    description: '在线路由追踪分析',
    tags: ['traceroute', '路由', '追踪', '网络'],
  },
  {
    id: 'dns-query',
    name: 'DNS 查询',
    icon: 'globe',
    category: 'network',
    description: '在线 DNS 解析查询',
    tags: ['dns', '解析', '域名', '网络'],
  },
  {
    id: 'find-ping',
    name: 'FindPing',
    icon: 'compass',
    category: 'network',
    description: '查找最近的 Ping 服务器',
    tags: ['findping', 'ping', '服务器', '网络'],
  },
  {
    id: 'localhost-net',
    name: '本地网络',
    icon: 'network',
    category: 'network',
    description: '查看本地网络信息',
    tags: ['localhost', '本地', '网络', '局域网'],
  },
  // 格式转换
  {
    id: 'image-convert',
    name: '图片格式转换',
    icon: 'convert',
    category: 'conversion',
    description: 'JPG/PNG/WebP/BMP/GIF 图片格式互转',
    tags: ['image', 'convert', '图片', '格式', '转换', 'jpg', 'png', 'webp'],
  },
  {
    id: 'data-convert',
    name: '数据格式转换',
    icon: 'file_type',
    category: 'conversion',
    description: 'CSV/JSON/XML 数据格式互转',
    tags: ['data', 'convert', '数据', '格式', '转换', 'csv', 'json', 'xml'],
  },
  {
    id: 'audio-convert',
    name: '音频格式转换',
    icon: 'music',
    category: 'conversion',
    description: 'MP3/WAV/FLAC/AAC/OGG/M4A/WMA 常见音频格式互转',
    tags: ['audio', 'convert', '音频', '格式', '转换', 'mp3', 'wav', 'flac', 'aac', 'ogg', 'm4a', 'wma'],
  },
  {
    id: 'special-format-convert',
    name: '特殊格式转换',
    icon: 'alert',
    category: 'conversion',
    description: '跳转到第三方特殊音频格式转换页面，含风险提示',
    tags: ['special', 'audio', 'convert', '特殊格式', '音频', '转换', 'mflac', 'mgg', 'kgm', 'ncm', 'kwm'],
  },
  // 图片工具
  {
    id: 'image-compress',
    name: '图片压缩',
    icon: 'compress',
    category: 'image',
    description: '在线压缩图片文件大小',
    tags: ['image', 'compress', '压缩', '图片'],
  },
  {
    id: 'image-crop',
    name: '图片裁剪',
    icon: 'crop',
    category: 'image',
    description: '在线裁剪和调整图片尺寸',
    tags: ['image', 'crop', '裁剪', '图片'],
  },
  {
    id: 'image-base64',
    name: '图片转 Base64',
    icon: 'image',
    category: 'encoding',
    description: '将图片转换为 Base64 编码字符串',
    tags: ['image', 'base64', '图片', '编码'],
  },
  {
    id: 'image-to-pdf',
    name: '图片转PDF',
    icon: 'file_image',
    category: 'conversion',
    description: '将多张图片合并为PDF文件',
    tags: ['image', 'pdf', '图片', '合并', '转换'],
  },
  {
    id: 'gif-maker',
    name: 'GIF制作',
    icon: 'film',
    category: 'image',
    description: '将多张图片合成为GIF动图',
    tags: ['gif', '动图', '制作', '图片', '动画'],
  },
  {
    id: 'animated-avatar',
    name: '动态头像生成器',
    icon: 'sparkles',
    category: 'image',
    description: '为头像添加动画效果并导出GIF',
    tags: ['avatar', '头像', '动画', 'gif', '特效'],
  },
  {
    id: 'image-color-picker',
    name: '图片取色器',
    icon: 'paint_bucket',
    category: 'image',
    description: '从图片中提取颜色值',
    tags: ['color', '取色', '颜色', '图片', '拾色器'],
  },
  {
    id: 'ocr-extract',
    name: 'OCR文字识别',
    icon: 'scan_text',
    category: 'image',
    description: '识别图片中的中英文文字',
    tags: ['ocr', '文字识别', '识别', '提取', '图片'],
  },
  {
    id: 'image-upscale',
    name: 'AI图片超分辨率',
    icon: 'wand',
    category: 'image',
    description: '跳转至在线 AI 图片无损放大工具',
    tags: ['image', 'upscale', '超分', '放大', 'AI', '图片', 'realesrgan'],
  },
  // 安全工具
  {
    id: 'hash-gen',
    name: '哈希生成',
    icon: 'hash',
    category: 'security',
    description: '生成文本的 MD5 / SHA-1 / SHA-256 哈希值',
    tags: ['hash', 'md5', 'sha', '哈希', '加密'],
  },
  {
    id: 'hmac-gen',
    name: 'HMAC 签名',
    icon: 'lock',
    category: 'security',
    description: '使用密钥生成 HMAC 签名',
    tags: ['hmac', '签名', '安全', '密钥'],
  },
  {
    id: 'http-tester',
    name: 'HTTP 请求测试器',
    icon: 'http',
    category: 'network',
    description: '发送 HTTP 请求并查看响应',
    tags: ['http', 'request', '请求', '测试', 'api'],
  },
  {
    id: 'symmetric-crypto',
    name: '对称加密',
    icon: 'lock',
    category: 'security',
    description: 'AES-256-GCM / CBC 加密解密',
    tags: ['aes', '加密', '对称', 'crypto', '密钥'],
  },
  {
    id: 'caesar-cipher',
    name: '凯撒密码',
    icon: 'swap_horiz',
    category: 'security',
    description: '字母位移加密，支持暴力枚举',
    tags: ['caesar', '凯撒', '位移', '密码', '暴力'],
  },
  {
    id: 'rail-fence',
    name: '栅栏密码',
    icon: 'grid_view',
    category: 'security',
    description: 'Z 字形排列转置加密',
    tags: ['rail', 'fence', '栅栏', '密码', '转置'],
  },
  // 视频工具
  {
    id: 'video-convert',
    name: '视频格式转换',
    icon: 'convert',
    category: 'conversion',
    description: 'MP4/MOV/AVI/MKV/FLV/WMV 视频格式互转',
    tags: ['video', 'convert', '视频', '格式', '转换', 'mp4', 'mov', 'avi', 'mkv'],
  },
  {
    id: 'video-to-gif',
    name: '视频转GIF',
    icon: 'film',
    category: 'conversion',
    description: '将视频片段转换为 GIF 动图',
    tags: ['video', 'gif', '视频', '动图', '转换'],
  },
  {
    id: 'video-to-mp3',
    name: '视频转MP3',
    icon: 'music',
    category: 'conversion',
    description: '从视频中提取音频为 MP3 文件',
    tags: ['video', 'mp3', '音频', '提取', '视频'],
  },
  {
    id: 'video-compress',
    name: '视频压缩',
    icon: 'zap',
    category: 'conversion',
    description: '压缩视频文件大小，支持 4K/高清',
    tags: ['video', 'compress', '压缩', '视频', '4k', '高清'],
  },
  // PDF 工具
  {
    id: 'pdf-merge',
    name: 'PDF 合并',
    icon: 'description',
    category: 'conversion',
    description: '将多个 PDF 文件合并为一个，支持拖拽排序',
    tags: ['pdf', 'merge', '合并', 'PDF'],
  },
  {
    id: 'pdf-split',
    name: 'PDF 拆分',
    icon: 'description',
    category: 'conversion',
    description: '将 PDF 拆分为单页或按页码范围提取',
    tags: ['pdf', 'split', '拆分', '提取', 'PDF'],
  },
  {
    id: 'pdf-compress',
    name: 'PDF 压缩',
    icon: 'compress',
    category: 'conversion',
    description: '压缩 PDF 文件大小，移除冗余数据',
    tags: ['pdf', 'compress', '压缩', 'PDF'],
  },
  // 开发者工具
  {
    id: 'timestamp',
    name: '时间戳转换',
    icon: 'history',
    category: 'generator',
    description: 'Unix 时间戳与人类可读日期互转',
    tags: ['timestamp', '时间戳', 'unix', '日期', '转换'],
  },
  {
    id: 'cron-parser',
    name: 'Cron 表达式解析',
    icon: 'history',
    category: 'generator',
    description: '解析 Cron 表达式，查看含义和未来执行时间',
    tags: ['cron', '定时', '表达式', '解析', '定时任务'],
  },
  // 文件预览
  {
    id: 'file-preview',
    name: 'Word/PDF 预览',
    icon: 'preview',
    category: 'text',
    description: '在线预览 Word (.docx) 和 PDF 文件，本地处理不上传',
    tags: ['word', 'pdf', 'docx', '预览', '文件', '文档'],
  },
];

export function getRegistry(): ToolMeta[] {
  return registry;
}

export function getToolMeta(id: string): ToolMeta | undefined {
  return registry.find(t => t.id === id);
}

export function getToolsByCategory(category: ToolCategory): ToolMeta[] {
  return registry.filter(t => t.category === category);
}
